//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCalc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetCalc.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address block.
        /// </summary>
        public static string AddressBlock {
            get {
                return ResourceManager.GetString("AddressBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETCALC.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove advertisements.
        /// </summary>
        public static string BuyToRemoveAdvertisements {
            get {
                return ResourceManager.GetString("BuyToRemoveAdvertisements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the subnet mask.
        /// </summary>
        public static string ChooseNetMask {
            get {
                return ResourceManager.GetString("ChooseNetMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the number of subnets.
        /// </summary>
        public static string ChooseSubnets {
            get {
                return ResourceManager.GetString("ChooseSubnets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subnet mask.
        /// </summary>
        public static string DetailsSubnetMask {
            get {
                return ResourceManager.GetString("DetailsSubnetMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First usable address.
        /// </summary>
        public static string FirstUsable {
            get {
                return ResourceManager.GetString("FirstUsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP address.
        /// </summary>
        public static string InvalidIP {
            get {
                return ResourceManager.GetString("InvalidIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last usable address.
        /// </summary>
        public static string LastUsable {
            get {
                return ResourceManager.GetString("LastUsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the first 500 results were shown..
        /// </summary>
        public static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List subnets.
        /// </summary>
        public static string ListSubnets {
            get {
                return ResourceManager.GetString("ListSubnets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cidr calculator.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask.
        /// </summary>
        public static string NetBits {
            get {
                return ResourceManager.GetString("NetBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network ID.
        /// </summary>
        public static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of hosts.
        /// </summary>
        public static string NumberOfHosts {
            get {
                return ResourceManager.GetString("NumberOfHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate and review.
        /// </summary>
        public static string RateAndReview {
            get {
                return ResourceManager.GetString("RateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC 3021 compliant.
        /// </summary>
        public static string RFC3021Compliant {
            get {
                return ResourceManager.GetString("RFC3021Compliant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subnet details.
        /// </summary>
        public static string SubnetDetails {
            get {
                return ResourceManager.GetString("SubnetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subnet Mask.
        /// </summary>
        public static string SubnetMask {
            get {
                return ResourceManager.GetString("SubnetMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subnets.
        /// </summary>
        public static string Subnets {
            get {
                return ResourceManager.GetString("Subnets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can tap on the list of subnets to view its details.
        /// </summary>
        public static string Toast {
            get {
                return ResourceManager.GetString("Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcard subnet mask.
        /// </summary>
        public static string WildCardSubnetMask {
            get {
                return ResourceManager.GetString("WildCardSubnetMask", resourceCulture);
            }
        }
    }
}
